export const sentences: string[] = [
  // Dyr
  "Katten sover i sin kurv.",
  "Hunden løber rundt i haven.",
  "Fisken svømmer i den blå sø.",
  "Fuglen synger en smuk sang.",
  "Kaninen hopper over græsset.",
  "Hesten galopperer hen over marken.",
  "Koen står og spiser græs.",
  "Grisen ruller sig i mudderet.",
  "Ænderne svømmer på dammen.",
  "Sommerfuglen har flotte vinger.",
  "Frøen hoppede ud i vandet.",
  "Musen løb ind i sit hul.",
  "Uglen sidder i det store træ.",
  "Elefanten er et stort dyr.",
  "Løven er kongen af junglen.",
  "Pingvinen kan ikke flyve.",
  "Papegøjen kan sige mange ord.",
  "Slangen kryber stille gennem græsset.",
  "Skildpadden bevæger sig langsomt.",
  "Delfinen hopper op af vandet.",
  "Bjørnen sover hele vinteren.",
  "Ræven lister sig gennem skoven.",
  "Den lille kat fangede en mus.",
  "Min hund elsker at lege med bold.",
  "Vi så en stor fugl i parken.",
  "Hamsterens hjul drejer hele natten.",
  "Gederne klatrer op på klippen.",
  "Fårene står ude på marken.",
  "Den hvide svane svømmer på søen.",
  "Mariehønen har røde vinger med prikker.",

  // Familie og venner
  "Min mor laver den bedste mad.",
  "Min far læser en bog for mig.",
  "Min søster tegner en fin tegning.",
  "Min bror spiller fodbold i haven.",
  "Bedstemor bager altid lækre kager.",
  "Bedstefar fortæller sjove historier.",
  "Min bedste ven bor lige ved siden af.",
  "Vi leger sammen hver eneste dag.",
  "Min familie er den bedste i verden.",
  "Vi holder altid jul sammen.",
  "Min kusine kommer på besøg i morgen.",
  "Min onkel har en stor båd.",
  "Min tante laver de bedste pandekager.",
  "Vi spiser aftensmad sammen hver dag.",
  "Min lillebror lærer at gå nu.",
  "Min storesøster hjælper mig med lektier.",
  "Vi tager på ferie med hele familien.",
  "Min ven og jeg bygger med klodser.",
  "Vi griner altid meget sammen.",
  "Min nabo har en sød lille hund.",

  // Skole
  "I dag har vi matematik i skolen.",
  "Læreren skriver på tavlen med kridt.",
  "Vi læser en sjov bog i klassen.",
  "Frikvarteret er det bedste på dagen.",
  "Jeg har min madpakke med i skolen.",
  "Vi tegner og maler i billedkunst.",
  "I dag lærte vi om dinosaurer.",
  "Min skoletaske er blå og rød.",
  "Vi synger sange i musikundervisningen.",
  "Klokken ringer og timen begynder.",
  "Vi har idræt to gange om ugen.",
  "Jeg sidder ved siden af min ven.",
  "Vi laver gruppearbejde i dansk.",
  "Min blyant er næsten helt brugt op.",
  "Vi har fået nye bøger i klassen.",
  "Læreren gav os en sjov opgave.",
  "Vi øver os på at stave nye ord.",
  "I dag er det den sidste skoledag.",
  "Vi har en hyggelig klasselærer.",
  "Min yndlingsfag er matematik.",

  // Mad og drikke
  "Jeg elsker at spise pandekager.",
  "Vi drikker varm kakao om vinteren.",
  "Æblerne er røde og saftige.",
  "Mormor laver den bedste suppe.",
  "Vi spiser rugbrød til frokost.",
  "Isen smager godt om sommeren.",
  "Vi bager boller med chokolade.",
  "Jordbærrene er søde og røde.",
  "Vi laver pizza med ost og tomat.",
  "Min yndlingsret er spaghetti.",
  "Vi plukker bær ude i skoven.",
  "Bananerne skal være gule og modne.",
  "Vi drikker mælk til aftensmaden.",
  "Kagen er pyntet med flødeskum.",
  "Gulerødderne vokser i haven.",
  "Vi spiser havregryn til morgenmad.",
  "Popcorn smager godt til en film.",
  "Brødet er friskbagt fra bageren.",
  "Vi koger kartofler til aftensmad.",
  "Honning smager sødt på brødet.",

  // Natur
  "Solen skinner på den blå himmel.",
  "Det regner udenfor i dag.",
  "Bladene falder ned fra træerne.",
  "Blomsterne blomstrer i haven.",
  "Det sner og alt er hvidt.",
  "Regnbuen har mange flotte farver.",
  "Bølgerne slår mod stranden.",
  "Træerne er høje og grønne.",
  "Skyerne danser hen over himlen.",
  "Vinden blæser i mit hår.",
  "Søen er stille og blank som et spejl.",
  "Bækkens vand risler stille forbi.",
  "Stenene på stranden er glatte og runde.",
  "De vilde blomster gror langs vejen.",
  "Stjernerne lyser op på nattehimlen.",
  "Månen er fuld og rund i aften.",
  "Det er tåget ude i dag.",
  "Skovens træer er meget gamle.",
  "Vi finder svampe i skoven om efteråret.",
  "Isen på søen er tyk nok til at gå på.",

  // Årstider
  "Om foråret springer blomsterne ud.",
  "Om sommeren bader vi i havet.",
  "Om efteråret samler vi kastanjer.",
  "Om vinteren bygger vi en snemand.",
  "Foråret er min yndlingsårstid.",
  "Sommeren er varm og dejlig.",
  "Efteråret har mange flotte farver.",
  "Vinteren er kold men også hyggelig.",
  "Vi flyver med drager om foråret.",
  "Vi spiser is på stranden om sommeren.",
  "Bladene bliver røde og gule om efteråret.",
  "Vi kører på slæde om vinteren.",
  "Solen står højt om sommeren.",
  "Det bliver mørkt tidligt om vinteren.",
  "Vi planter frø i haven om foråret.",
  "Det blæser meget om efteråret.",
  "Fuglene flyver sydpå om vinteren.",
  "Vi griller pølser i haven om sommeren.",
  "Regnen falder tit om efteråret.",
  "Sneen dækker alt om vinteren.",

  // Leg og hobby
  "Vi bygger et stort sandslot.",
  "Jeg elsker at tegne og male.",
  "Vi spiller bold ude i parken.",
  "Hun cykler rundt i kvarteret.",
  "Vi leger gemmeleg i haven.",
  "Han bygger med sine klodser.",
  "Vi hopper på trampolinen.",
  "Jeg læser en spændende bog.",
  "Vi danser til vores yndlingsmusik.",
  "Hun laver fine perlearmbånd.",
  "Vi bager småkager med glasur.",
  "Han samler på frimærker.",
  "Vi spiller brætspil i weekenden.",
  "Jeg løber om kap med min ven.",
  "Vi klatrer i træer i skoven.",
  "Hun spiller klaver hver dag.",
  "Vi synger sange sammen i koret.",
  "Han tegner en tegneserie.",
  "Vi laver en drageflyvning.",
  "Jeg spiller guitar efter skole.",

  // Kroppen
  "Jeg børster mine tænder hver morgen.",
  "Vi vasker vores hænder inden mad.",
  "Mine øjne er blå som himlen.",
  "Jeg har langt brunt hår.",
  "Vi skal sove mindst ti timer.",
  "Mine fødder er trætte efter turen.",
  "Vi strækker ud inden vi løber.",
  "Hjertet banker i mit bryst.",
  "Ørerne hjælper os med at høre.",
  "Næsen kan lugte de gode kager.",

  // Hjem og hverdag
  "Vi rydder op på vores værelser.",
  "Huset har et rødt tag.",
  "Køkkenet dufter af friskbagt brød.",
  "Vi har en stor have med æbletræer.",
  "Sofaen i stuen er blød og behagelig.",
  "Lampen lyser varmt i stuen.",
  "Vi vasker tøj hver lørdag.",
  "Trappen knirker når vi går op.",
  "Vinduet er åbent og solen skinner ind.",
  "Vi dækker bord til aftensmaden.",
  "Postkassen er fuld af breve.",
  "Garagen er fuld af cykler.",
  "Vi fejer bladene væk fra indkørslen.",
  "Det er tid til at gå i seng.",
  "Vi hænger jakker op i garderoben.",
  "Badeværelset er rent og pænt.",
  "Vi slukker lyset når vi går ud.",
  "Vi lufter hunden inden sengetid.",
  "Morgenmaden står klar på bordet.",
  "Vi lukker døren når vi går hjemmefra.",

  // Transport
  "Bussen kører os til skolen.",
  "Toget kører hurtigt gennem landskabet.",
  "Vi sejler med færgen over fjorden.",
  "Flyvemaskinen letter fra lufthavnen.",
  "Cyklen har to hjul og en klokke.",
  "Bilen holder parkeret i garagen.",
  "Vi kører i tog til København.",
  "Helikopteren flyver hen over byen.",
  "Skibet sejler ud på det store hav.",
  "Vi tager metroen ind til byen.",

  // Eventyr og fantasi
  "Prinsessen bor i et stort slot.",
  "Dragen spyr ild op i luften.",
  "Ridderen rider på sin hvide hest.",
  "Trolden bor under den gamle bro.",
  "Feen har et tryllestav af guld.",
  "Piraten leder efter den skjulte skat.",
  "Havfruen svømmer dybt i havet.",
  "Troldmanden laver en magisk drik.",
  "Enhjørningen har et horn på panden.",
  "Ridderne beskytter det store slot.",
  "Skattekortet viser vejen til guldet.",
  "Den flyvende tæppe flyver over byen.",
  "Heksen brygger en grøn trylledrik.",
  "Dværgene graver efter ædelstene.",
  "Elverne bor dybt inde i skoven.",
  "Den magiske bog kan opfylde ønsker.",
  "Prinsessen blev reddet af den tapre helt.",
  "Dragen vogter over den gyldne skat.",
  "Nissen gemmer sig på loftet.",
  "Det forheksede spejl kan tale.",

  // Vejret
  "I dag er det solskin og varmt.",
  "Det blæser en hel del derude.",
  "Tordenen brager højt over os.",
  "Lynene blinker på den mørke himmel.",
  "Det hagler små isklumper ned.",
  "Tågen ligger tæt over markerne.",
  "Det fryser ude og vandet bliver til is.",
  "Vi tager paraply med når det regner.",
  "Regndråberne trommer på vinduet.",
  "Solen varmer dejligt i dag.",

  // Sport
  "Vi spiller fodbold på den store bane.",
  "Hun svømmer hurtigere end alle andre.",
  "Vi løber om kap i idrætstimen.",
  "Han scorer et mål med et flot spark.",
  "Vi spiller håndbold i hallen.",
  "Badmintonbolden flyver over nettet.",
  "Vi hopper højdespring til idræt.",
  "Holdet vinder kampen med tre mål.",
  "Vi dyrker gymnastik hver onsdag.",
  "Hun danser ballet efter skoletid.",
  "Skateboard er sjovt at køre på.",
  "Vi spiller tennis i parken.",
  "Han løber en lang tur hver morgen.",
  "Vi cykler et langt cykelløb.",
  "Svømmehallen er åben hele ugen.",

  // Farver og former
  "Himlen er blå og skyerne er hvide.",
  "Solen er gul og rund som en bold.",
  "Græsset er grønt efter regnen.",
  "Jordbærret er rødt og sødt.",
  "Appelsinen er orange og rund.",
  "Cirklen har ingen hjørner.",
  "Trekanten har tre sider.",
  "Firkanten har fire lige lange sider.",
  "Regnbuens farver er helt fantastiske.",
  "Den lilla blomst dufter dejligt.",

  // Tal og bogstaver
  "Jeg kan tælle til hundrede nu.",
  "Alfabetet har niogtyve bogstaver.",
  "To plus to er lig med fire.",
  "Vi øver os på gangetabellen.",
  "Bogstavet A er det første i alfabetet.",
  "Jeg kan stave mit eget navn.",
  "Tallene går fra nul til ni.",
  "Vi lærer at regne med plus og minus.",
  "Der er ti fingre på mine hænder.",
  "Bogstaverne danner ord og sætninger.",

  // Følelser
  "Jeg er glad i dag.",
  "Hun er stolt af sin tegning.",
  "Vi griner af den sjove historie.",
  "Han er modig og stærk.",
  "Vi er spændte på turen i morgen.",
  "Hun smiler til alle hun møder.",
  "Jeg er taknemmelig for mine venner.",
  "Vi er glade for det gode vejr.",
  "Han er ivrig efter at lære nyt.",
  "Det gør mig glad at hjælpe andre.",

  // Steder i Danmark
  "København er hovedstaden i Danmark.",
  "Legoland ligger i Billund.",
  "Tivoli er en gammel forlystelsespark.",
  "Den lille havfrue sidder ved havnen.",
  "Vi besøger Odense i sommerferien.",
  "Aalborg ligger i Nordjylland.",
  "Aarhus er en stor by i Jylland.",
  "Bornholm er en smuk ø i Østersøen.",
  "Skagen ligger helt oppe i toppen.",
  "Roskilde har en stor gammel domkirke.",
  "Vi tog færgen til Samsø i sommer.",
  "Kronborg Slot ligger i Helsingør.",
  "Vi cyklede over Storebæltsbroen.",
  "Vadehavet er et flot naturområde.",
  "Møns Klint har høje hvide klipper.",

  // Musik og lyd
  "Musikken spiller højt fra radioen.",
  "Vi synger fødselsdagssangen for ham.",
  "Trommerne laver en høj lyd.",
  "Guitaren har seks strenge.",
  "Vi spiller xylofon i musik.",
  "Klokken ringer højt og klart.",
  "Fuglens sang lyder så smuk.",
  "Vi klapper i takt til musikken.",
  "Fløjten laver en blød og fin tone.",
  "Vi lytter til musik inden sengetid.",

  // Kreativitet
  "Vi tegner en regnbue med farver.",
  "Han klipper figurer ud i papir.",
  "Vi limer glimmer på vores kort.",
  "Hun former dyr ud af modellervoks.",
  "Vi maler et stort billede af havet.",
  "Han folder en papirflyver.",
  "Vi laver masker af pap og farver.",
  "Hun syr en lille pude til sin dukke.",
  "Vi bygger en raket af papruller.",
  "Han laver en fin collage.",

  // Helligdage og fester
  "Juleaften spiser vi and og ris.",
  "Vi danser om juletræet og synger.",
  "Nytårsaften skyder vi fyrværkeri.",
  "Til fastelavn slår vi katten af tønden.",
  "Vi farver æg til påske.",
  "Påskeharen gemmer æg i haven.",
  "Til halloween klæder vi os ud.",
  "Vi holder fødselsdag med kage og flag.",
  "Sankt Hans aften tænder vi bål.",
  "Vi pynter huset med lyskæder til jul.",

  // Dagligdags handlinger
  "Jeg tager mine sko på inden vi går.",
  "Vi pakker madpakken aftenen inden.",
  "Hun binder sine snørebånd selv.",
  "Vi cykler til skole hver morgen.",
  "Han hænger sin jakke op på krogen.",
  "Vi spiser frokost i klassen.",
  "Jeg rydder mit skrivebord efter lektier.",
  "Vi går en tur med hunden efter skole.",
  "Hun læser lektier ved køkkenbordet.",
  "Vi gør os klar til sengetid klokken otte.",

  // Klæder
  "Jeg tager mine gummistøvler på.",
  "Min vinterjakke er varm og tyk.",
  "Vi har hue og vanter på om vinteren.",
  "Hendes kjole er gul med blomster.",
  "Han finder sine fodboldstøvler frem.",
  "Vi tager regntøj på når det regner.",
  "Mine sokker har sjove mønstre.",
  "Tørklædet holder min hals varm.",
  "Vi skifter til indendørssko i skolen.",
  "Hendes nye sko er røde og blanke.",

  // Teknologi
  "Vi ser en film sammen på sofaen.",
  "Computeren starter langsomt op.",
  "Vi tager et billede med kameraet.",
  "Telefonen ringer i lommen.",
  "Vi lytter til en podcast sammen.",
  "Printeren laver en kopi af billedet.",
  "Vi lærer at skrive på tastaturet.",
  "Skærmen lyser op i mørket.",
  "Vi spiller et sjovt computerspil.",
  "Robotten kan bevæge sig selv.",

  // Bøger og historier
  "Vi læser en godnathistorie i sengen.",
  "Bogen handler om en modig pige.",
  "Biblioteket har mange sjove bøger.",
  "Vi finder en ny bog at læse.",
  "Historien har en lykkelig slutning.",
  "Billedbogen har flotte tegninger.",
  "Vi læser højt for hinanden.",
  "Bogen om dragen er min favorit.",
  "Vi låner bøger på biblioteket.",
  "Den sjove bog får os til at grine.",

  // Rummet og verdensrummet
  "Månen lyser op om natten.",
  "Stjernerne blinker på himlen.",
  "Raketten flyver ud i rummet.",
  "Astronauten svæver i rumstationen.",
  "Jorden er rund som en kugle.",
  "Solen er en kæmpe stor stjerne.",
  "Mars er den røde planet.",
  "Vi kigger på stjerner med en kikkert.",
  "Rumskibet rejser til en fjern planet.",
  "Satellitten kredser om Jorden.",

  // Hav og strand
  "Vi bygger sandslotte på stranden.",
  "Bølgerne skyller ind over sandet.",
  "Krabben kravler over stenene.",
  "Vi finder muslingeskaller i sandet.",
  "Fyrtårnet lyser ud over havet.",
  "Vi bader i det varme hav.",
  "Søstjernerne ligger på havbunden.",
  "Vi sejler en lille jolle på fjorden.",
  "Havmågen flyver over bølgerne.",
  "Vi samler sten og skaller på stranden.",

  // Sjove sætninger
  "Aben spiste en banan på hovedet.",
  "Den flyvende ko landede i træet.",
  "Fisken cyklede til skole i dag.",
  "Elefanten prøvede at gemme sig bag lampen.",
  "Katten bar en hat og dansede vals.",
  "Snegleløbet varede hele dagen.",
  "Pingvinen stod på ski ned ad bakken.",
  "Frøen sang en popsang for fuglene.",
  "Den talende hund bestilte en pizza.",
  "Kaninen vandt guld i svømning.",
  "Papegøjen blev pilot og fløj et fly.",
  "Girafffen kunne ikke se sine egne fødder.",
  "Musen kørte lastbil gennem byen.",
  "Den dansende bjørn vandt konkurrencen.",
  "Krokodillen gik til tandlægen.",

  // Mere hverdag
  "Vi tænder stearinlys i vinduet.",
  "Klokken er syv og vi skal i skole.",
  "Bussen kommer om fem minutter.",
  "Vi køber frugt og grønt i butikken.",
  "Avisen ligger på dørmåtten.",
  "Vi ser tegnefilm om morgenen.",
  "Katten sidder i vinduet og kigger ud.",
  "Vi cykler langs stranden i solskinnet.",
  "Fuglene sidder på elledningen.",
  "Vi planter et nyt træ i haven.",

  // Venskab
  "En god ven lytter altid til dig.",
  "Vi deler vores legetøj med hinanden.",
  "Min ven trøster mig når jeg er ked af det.",
  "Vi finder altid på noget sjovt sammen.",
  "Det er vigtigt at være en god ven.",
  "Vi hjælper hinanden med opgaverne.",
  "Min ven gør mig altid glad.",
  "Vi har kendt hinanden i mange år.",
  "Vi laver en hemmelig klub sammen.",
  "Gode venner holder altid sammen.",

  // Drømme og ønsker
  "Jeg drømmer om at flyve en dag.",
  "Hun vil gerne være dyrlæge.",
  "Han drømmer om at rejse til månen.",
  "Vi håber på sne til jul i år.",
  "Jeg vil gerne lære at svømme bedre.",
  "Hun ønsker sig en hundehvalp.",
  "Han vil bygge det højeste tårn.",
  "Vi drømmer om en lang sommerferie.",
  "Jeg vil gerne tegne tegneserier.",
  "Hun vil gerne spille i et band.",

  // Sikkerhed og regler
  "Vi kigger os altid godt for inden vi krydser.",
  "Cykelhjelmen beskytter vores hoved.",
  "Vi holder i hånd når vi går over vejen.",
  "Selen skal altid være spændt i bilen.",
  "Vi løber aldrig ved svømmebassinet.",
  "Det er vigtigt at lytte til de voksne.",
  "Vi vasker hænder inden vi spiser.",
  "Vi rører aldrig ved komfuret alene.",
  "Reflekserne lyser op i mørket.",
  "Vi følger reglerne i trafikken.",

  // Gøremål i hjemmet
  "Vi hjælper med at dække bordet.",
  "Hun tørrer støv af i stuen.",
  "Vi sorterer vores legetøj i kasser.",
  "Han hænger sit håndklæde op.",
  "Vi reder vores seng om morgenen.",
  "Vi hjælper med at bage en kage.",
  "Hun vander blomsterne på altanen.",
  "Vi folder det rene tøj sammen.",
  "Han støvsuger sit eget værelse.",
  "Vi vasker op efter aftensmaden.",

  // Korte og lette
  "Det er en god dag.",
  "Jeg kan godt lide dig.",
  "Solen er oppe nu.",
  "Vi leger ude i dag.",
  "Katten siger mjav.",
  "Hunden logrer med halen.",
  "Bolden er rød og stor.",
  "Vi løber en tur.",
  "Han griner højt.",
  "Hun smiler til mig.",
  "Det er tid til mad.",
  "Vi hopper i vandpytterne.",
  "Isen smelter i solen.",
  "Fuglen flyver højt.",
  "Vi går hen til parken.",

  // Lidt sværere sætninger
  "Vi besøgte det naturhistoriske museum.",
  "Strandturen var den bedste oplevelse.",
  "Sommerhuset ligger tæt ved stranden.",
  "Vi cyklede hele vejen til biblioteket.",
  "Fødselsdagsfesten havde mange balloner.",
  "Akvariet havde de flotteste fisk.",
  "Vi lærte at lave fuglekasser i sløjd.",
  "Klassens hamster hedder Nansen.",
  "Regnvejret stoppede lige inden vi gik ud.",
  "Kartoffelsalat smager bedst om sommeren.",
  "Vi plantede solsikkefrø i små krukker.",
  "Svømmestævnet foregår på lørdag.",
  "Fodboldkampen endte uafgjort to mod to.",
  "Vi lavede pandekager med syltetøj.",
  "Lejrskolen varer fra mandag til fredag.",
  "Vi opdagede et egern i baghaven.",
  "Skøjteløb er sjovt når isen er tyk.",
  "Vindmøllerne drejer rundt i blæsten.",
  "Vi lavede en sneboldkamp efter skole.",
  "Cirkusforestillingen havde akrobater.",
  "Landmanden høster kornet om efteråret.",
  "Bagerens wienerbrød er altid friske.",
  "Vi tog rutsjebanen tre gange i træk.",
  "Fyrtårnet blinkede i den mørke nat.",
  "Vi samlede skrald langs vejen i dag.",

  // Flere blandede sætninger
  "Vi fandt en tudse nede ved åen.",
  "Kirsebærtræet blomstrer om foråret.",
  "Drengen byggede en stor borg af sne.",
  "Pigen samlede vilde blomster til vasen.",
  "Vi lavede en snemand med gulerodsnæse.",
  "Min cykel har fået nye dæk i dag.",
  "Vi tog toget til stranden i går.",
  "Hanen galer tidligt hver morgen.",
  "Vi bagte kanelboller til hele klassen.",
  "Den gamle mølleå løber gennem byen.",
  "Vi legede fangeleg i den store park.",
  "Æbletræet bærer mange frugter i år.",
  "Vi hopper i hø ude på bondegården.",
  "Pigen fandt en fin sten ved stranden.",
  "Vi sejlede i kano på den stille sø.",
  "Drengen fløjtede en munter melodi.",
  "Vi lavede en hytte af grene i skoven.",
  "Solnedgangen var helt orange og rød.",
  "Vi drak varm suppe efter den kolde tur.",
  "Min veninde flyttede til en ny by.",
  "Vi stod op tidligt for at se solopgangen.",
  "Bøgeskoven er så smuk om efteråret.",
  "Vi spillede kort og drak saftevand.",
  "Markerne er gule af raps om foråret.",
  "Vi ønsker os god sommer og sol i år.",
];

export function getRandomSentence(exclude?: string): string {
  const available = exclude
    ? sentences.filter((s) => s !== exclude)
    : sentences;
  return available[Math.floor(Math.random() * available.length)];
}
